//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_Complejidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Centro_Poblado
    {
        public string UBIGEO { get; set; }
        public string DEP { get; set; }
        public string PROV { get; set; }
        public string DIST { get; set; }
        public string CODCP { get; set; }
        public string NOMCP { get; set; }
        public string MNOMCP { get; set; }
        public string CAPITAL { get; set; }
        public string CON_IE { get; set; }
        public string NIVEL { get; set; }
        public string CPINEI { get; set; }
        public string CPINEI2 { get; set; }
        public string CPINEI_BKP { get; set; }
        public string FUENTE_G { get; set; }
        public string Z { get; set; }
        public Nullable<decimal> XGD { get; set; }
        public Nullable<decimal> YGD { get; set; }
    }
}
